name: Release

on:
  workflow_dispatch:
  release:
    types: [published]
  push:
    branches:
      - main
      - dev*
    paths:
      - "**/*.patch"
      - ".github/workflows/*.yml"
  pull_request:
    types: [opened, synchronize, reopened]
    paths:
      - "**/*.patch"
      - ".github/workflows/*.yml"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: archlinux/archlinux:base-devel
    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          pacman -Syu --needed --noconfirm patch python fontforge curl jq zip p7zip openssl

      - name: Get tag of Sarasa Gothic and Nerd Fonts
        run: |
          SARASA_TAG="$(curl -sL "https://api.github.com/repos/be5invis/Sarasa-Gothic/releases" | jq -r ".[0].tag_name")"
          SARASA_TAG=${SARASA_TAG:1}
          echo "SARASA_TAG=$SARASA_TAG" >> $GITHUB_ENV
          NERD_TAG="$(curl -sL "https://api.github.com/repos/ryanoasis/nerd-fonts/releases" | jq -r ".[0].tag_name")"
          echo "NERD_TAG=$NERD_TAG" >> $GITHUB_ENV

      - name: Cache Sarasa Gothic
        id: cache-sarasa
        uses: actions/cache@v2
        with:
          key: sarasa-gothic-${{ env.SARASA_TAG }}
          path: ./sarasa-gothic-ttf.7z

      - name: Cache Nerd Fonts
        id: cache-nerd
        uses: actions/cache@v2
        with:
          key: nerd-fonts-${{ env.NERD_TAG }}
          path: ./nerd-fonts.zip

      - name: Download Sarasa Gothic
        if: steps.cache-sarasa.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/be5invis/Sarasa-Gothic/releases/download/v${{ env.SARASA_TAG }}/sarasa-gothic-ttf-${{ env.SARASA_TAG }}.7z -o sarasa-gothic-ttf.7z

      - name: Download Nerd Fonts
        if: steps.cache-nerd.outputs.cache-hit != 'true'
        run: |
          curl -L https://github.com/ryanoasis/nerd-fonts/archive/refs/tags/${{ env.NERD_TAG }}.zip -o nerd-fonts.zip

      - name: Extract Sarasa Gothic and Nerd Fonts
        run: |
          7z x -osarasa-gothic sarasa-gothic-ttf.7z
          7z x nerd-fonts.zip
          mv nerd-fonts-${{ env.NERD_TAG }} nerd-fonts

      - name: Patch Nerd Fonts
        run: |
          patch ${GITHUB_WORKSPACE}/nerd-fonts/font-patcher ${GITHUB_WORKSPACE}/font-patcher.patch

      - name: Patch Sarasa Gothic Term SC
        run: |
          mkdir assets
          for FILE in `ls sarasa-gothic | grep sarasa-term-sc-`
          do
            ${GITHUB_WORKSPACE}/nerd-fonts/font-patcher -l --powerline --powerlineextra --fontawesome --fontawesomeextension --fontlogos --octicons ${GITHUB_WORKSPACE}/sarasa-gothic/${FILE} --out ${GITHUB_WORKSPACE}/assets
          done

      - name: Create ZIP archive
        if: github.event_name == 'release'
        run: |
          pushd assets || exit 1
          zip -9vr ${GITHUB_WORKSPACE}/sarasa-gothic-term-sc-nerd-ttf.zip .
          popd || exit 1
          FILE=${GITHUB_WORKSPACE}/sarasa-gothic-term-sc-nerd-ttf.zip
          DGST=$FILE.dgst
          for METHOD in {"md5","sha1","sha256","sha512"}
          do
            openssl dgst -$METHOD $FILE | sed 's/([^)]*)//g' >> $DGST
          done

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: sarasa-gothic-term-sc-nerd-ttf
          path: |
            ./assets/*

      - name: Upload to release
        uses: svenstaro/upload-release-action@v2
        if: github.event_name == 'release'
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ./sarasa-gothic-term-sc-nerd-ttf.zip*
          tag: ${{ github.ref }}
          file_glob: true
